Feat/create server chat
kSideProject/kpring pull request #140
Opened 2024-05-30 07:49 UTC by minisundev

## #️⃣연관된 이슈

#120

## 📝작업 내용

서버 전체 채팅 생성 기능을 구현했습니다

### 스크린샷 (선택)

## 💬리뷰 요구사항
ChatType에 의해 RoomChat인지 ServerChat인지에 따라 다른 메서드를 호출하는데 이게 저는 Service Layer에서 이뤄지는게 맞다고 생각하지만 Controller Layer에 있는게 더 적합한지 고민이 됩니다

2024-05-30 08:02 UTC, yudonggeun commented on chat/src/test/kotlin/kpring/chat/chat/api/v1/ChatControllerTest.kt
> +        val docs = result.expectStatus().isCreated().expectBody().json(om.writeValueAsString(data))
가독성을 위해서 라인을 분리해주면 더 좋을 것 같아요

2024-05-30 08:11 UTC, minisundev commented on chat/src/test/kotlin/kpring/chat/chat/api/v1/ChatControllerTest.kt
> +        val docs = result.expectStatus().isCreated().expectBody().json(om.writeValueAsString(data))
좋은 생각이네요

2024-05-30 08:12 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +
처음에는 그렇게 짰었는데 테스트코드 작성하다가 return값이 없는 every{}를 작성하기가 까다로워서 이렇게 바꿨어요 다시 해볼게요

2024-05-30 08:13 UTC, yudonggeun commented
> ChatType에 의해 RoomChat인지 ServerChat인지에 따라 다른 메서드를 호출하는데 이게 저는 Service Layer에서 이뤄지는게 맞다고 생각하지만 Controller Layer에 있는게 더 적합한지 고민이 됩니다

serverchat과 roomchat의 응답 데이터가 같은 것이 명확하면 service layer에서 분기 처리해서 구현하는 것이 좋아보이고요. 그렇지 않으면 controller layer에서 구현하는 것이 좋아보여요.

2024-05-30 08:39 UTC, minisundev commented
Service Layer의 return값 Boolean으로 바꿔봤어요

2024-05-30 08:44 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
> +    return ResponseEntity(ApiResponse(data = result, status = 201), HttpStatus.CREATED)
data에 true, false 담았을 때, 의미있는 데이터인가요?

2024-05-30 09:34 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
> +    return ResponseEntity(ApiResponse(data = result, status = 201), HttpStatus.CREATED)
아뇨 그렇지는 않은 것 같아요 null로 변경할게요!

2024-06-02 09:08 UTC, yudonggeun requested changes
ApiResponse 관련한 부분만 수정해주시면 merge 해도 무리가 없어 보이네요!
고생하셨어요.

2024-06-02 09:08 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
> +    }
when을 이용해서 enum을 분기처리하면 이후에 다른 채팅 타입이 추가되는 경우에는 컴파일 시점에서 분기 처리를 해야하는 것을 감지할 수 있어서 좀 더 좋을 것 같아요.

2024-06-02 09:08 UTC, yudonggeun commented on chat/src/test/kotlin/kpring/chat/chat/api/v1/ChatControllerTest.kt
> +            .json(om.writeValueAsString(ApiResponse(data = null, status = 201)))
data=null은 기본 생성자에서 초기화해주지 않나요? 사소하지만 그냥 제거하는 것은 어떨까요?

2024-06-02 09:08 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +  ): ApiResponse<*> {
`ApiResponse` 타입은 서비스 계층에서는 사용하지 않은 것이 어떨까요? Api 응답에 관한 로직인 controller에서 하는 것이 좋아보이네요.

2024-06-02 09:08 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +    return ApiResponse(data = null, status = 201)
`ApiResponse` 타입은 서비스 계층에서는 사용하지 않은 것이 어떨까요? Api 응답에 관한 로직인 controller에서 하는 것이 좋아보이네요.

2024-06-02 09:08 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +    return ApiResponse(data = null, status = 201)
`ApiResponse` 타입은 서비스 계층에서는 사용하지 않은 것이 어떨까요? Api 응답에 관한 로직인 controller에서 하는 것이 좋아보이네요.

2024-06-02 09:11 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
> +    }
오~ 좋은 지적이네요!👍👍✨

2024-06-02 09:11 UTC, minisundev commented on chat/src/test/kotlin/kpring/chat/chat/api/v1/ChatControllerTest.kt
> +            .json(om.writeValueAsString(ApiResponse(data = null, status = 201)))
좋은 생각인 것 같아요~!

2024-06-02 09:12 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +  ): ApiResponse<*> {
동의합니다!

2024-06-02 09:15 UTC, minisundev commented on chat/src/test/kotlin/kpring/chat/chat/api/v1/ChatControllerTest.kt
> +            .json(om.writeValueAsString(ApiResponse(data = null, status = 201)))
네 ~!

2024-06-02 11:36 UTC, yudonggeun approved these changes

2024-06-03 01:18 UTC, merged