[User] login, logout 테스트 작성
kSideProject/kpring pull request #26
Opened 2024-04-17 04:47 UTC by yudonggeun

## #️⃣연관된 이슈

#21 

## 📝작업 내용

로그인, 로그아웃 컨트롤러 테스트 코드를 작성하였습니다.
Controller 계층에 대한 테스트와 구현을 생성했습니다.

2024-04-17 11:13 UTC, vanillacake369 requested changes
성공 실패 케이스와 spread operator 로 rest docs 리팩토링 하신 점이 인상깊네용! :-)

2024-04-17 11:13 UTC, vanillacake369 commented on test/src/main/kotlin/kpring/test/restdoc/dsl/RestDocBuilder.kt
> +            MockMvcRestDocumentation.document(identifier, *builder.snippets.toTypedArray())
static [RestDocumentationResultHandler](https://docs.spring.io/spring-restdocs/docs/current/api/org/springframework/restdocs/mockmvc/RestDocumentationResultHandler.html)
[document](https://docs.spring.io/spring-restdocs/docs/current/api/org/springframework/restdocs/mockmvc/MockMvcRestDocumentation.html#document(java.lang.String,org.springframework.restdocs.snippet.Snippet...))([String](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/String.html) identifier, [Snippet](https://docs.spring.io/spring-restdocs/docs/current/api/org/springframework/restdocs/snippet/Snippet.html)... snippets)

Documents the API call with the given identifier using the given snippets in addition to any default snippets.

위 함수를 사용하신 거군요?

2024-04-17 11:13 UTC, vanillacake369 commented on user/src/main/kotlin/kpring/user/controller/LoginController.kt
> +        @RequestBody request: LogoutRequest
토큰을 헤더에 따로 집어넣지 않고 바디에 뺴신 부분이 인상적이네요!

혹시 이렇게 하신 의도가 있으신가용?

2024-04-17 11:13 UTC, vanillacake369 commented on user/src/test/kotlin/kpring/user/controller/LoginControllerTest.kt
> +            // docs
혹시 이 docs 부분은 각각의 테스트 메서드마다 다 일일이 구현해주어야하는건가요?? 🤔

2024-04-18 00:35 UTC, yudonggeun commented on user/src/test/kotlin/kpring/user/controller/LoginControllerTest.kt
> +            // docs
docs는 spring rest docs를 사용하는 코드를 구분하기 위해서 사용했어요. 테스트를 기반으로 문서를 생성해주는 코드이기 때문에 given, when, then보다는 새로운 카테고리로 분류를 하면 코드를 파악하는데 도움이 될 것 같다는 생각이에요.

그래서 spring rest docs로 문서를 생성하는 테스트 케이스이거나 문서화와 관련된 어떤 코드라면 `//docs`로 분리해서 작성하는 것을 권장해요.

2024-04-18 04:24 UTC, vanillacake369 commented on user/src/main/kotlin/kpring/user/controller/LoginController.kt
> +        @RequestBody request: LogoutRequest
> ***"자원을 삭제하는 것이 아니라 상태를 변경하는 기능이기 때문에 post가 적합하지 않을까?"***

너무 마음에 쏙 드는 근거네요!!

면접 보실 때 활용하셔도 너무 좋지 않을까 싶어요 ㅎㅎ

2024-04-18 04:26 UTC, vanillacake369 commented on user/src/test/kotlin/kpring/user/controller/LoginControllerTest.kt
> +            // docs
그렇군요!!
답변 감사합니다 👍

2024-04-18 04:26 UTC, vanillacake369 approved these changes

2024-04-18 04:36 UTC, merged