Feat/create chat
kSideProject/kpring pull request #37
Opened 2024-04-22 14:20 UTC by minisundev

## #️⃣연관된 이슈

#14

## 📝작업 내용

Chat 생성 기능을 구현했습니다~

2024-04-23 01:11 UTC, yudonggeun requested changes
첫 PR ㅊㅊ

2024-04-23 01:11 UTC, yudonggeun commented on chat/build.gradle.kts
> +    api(project(":auth"))
core모듈과 test 모듈을 제외하고는 의존성을 격리 시켜주세요

2024-04-23 01:11 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/model/Chat.kt
> +    var sentAt: LocalDateTime = LocalDateTime.now()
채팅을 보낸 일자는 생성된 이후에는 변경이 필요하지 않은 것 같아요.
그래서 var 대신 val를 사용하는 것이 좋아보여요.

2024-04-23 01:11 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/api/v1/ChatController.kt
> +        var result = chatService.createChat(request)
result에 할당 받은 값이 변경될 여지가 없다면 var보다는 val이 좋아보여요.

2024-04-23 01:16 UTC, yudonggeun commented on chat/src/main/resources/application.yml
> +    allow-bean-definition-overriding: true
어떤 목적으로 해당 설정을 사용한건가요? 무슨 역할을 하나요? 궁금해요!

2024-04-23 01:16 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/model/Chat.kt
> +    val room: String,
room은 어떤 정보인가요? 채팅방의 id인가요? 아니면 채팅방의 이름인가요?
채팅방을 식별할 수 있는 식별값(키) 데이터를 주입받도록 한건가요?

2024-04-23 10:29 UTC, minisundev commented on chat/src/main/resources/application.yml
> +    allow-bean-definition-overriding: true
Chat을 Entity로 만들어 두고 MongoDB에 저장하려 할 때 다음과 같은 에러가 발생해서 강제로 오버라이딩 가능하게 바꿨었어요! 근데 지금 JPA 아예 안 쓰려고 하니까 빼도 동작하네요! 

The bean 'chatRepository', defined in kpring.chat.repository.ChatRepository defined in @EnableMongoRepositories declared on MongoRepositoriesRegistrar.EnableMongoRepositoriesConfiguration, could not be registered. A bean with that name has already been defined in kpring.chat.repository.ChatRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration and overriding is disabled.

2024-04-23 10:30 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/model/Chat.kt
> +    val room: String,
채팅방 id입니다!

2024-04-23 10:30 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/api/v1/ChatController.kt
> +        var result = chatService.createChat(request)
넵!

2024-04-23 10:30 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/model/Chat.kt
> +    var sentAt: LocalDateTime = LocalDateTime.now()
넵!

2024-04-23 10:42 UTC, minisundev commented on chat/build.gradle.kts
> +    api(project(":auth"))
api는 현재 모듈을 사용하는 다른 모듈에게 해당 모듈의 공개 API를 노출시키고 현재 모듈의 변경이 외부 모듈에게 영향을 미칠 때, implementation은 현재 모듈 내부에서만 사용하고 다른 모듈이 현재 모듈의 내부 구현에 직접적으로 의존하지 않을 때 사용하는 거라고 하네요! 

core 모듈은 chat모듈에 의존적이라 api로 놔두는게 맞는 것 같습니다

2024-04-24 12:22 UTC, yudonggeun approved these changes
좋아용

2024-04-24 12:22 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/service/ChatService.kt
> +        val user = tokenResponse.body?.userId ?: throw GlobalException(ErrorCode.INVALID_TOKEN_BODY)
만약 토큰 검증이 실패하는 경우에는 실패시 처리 로직은 service에 존재하는데 토큰 검증 로직은 controller에 존재하면 파악이 힘들 것 같아요. 그래서 controller 혹은 service에서 토큰 검증 및 조회 기능을 통합하는 것이 좋다고 생각이 들어요.

2024-04-24 12:22 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/service/ChatService.kt
> +        )
200의 코드가 필요한 정보인가요? 필요하다면 왜 필요한가요?

2024-04-24 12:24 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/service/ChatService.kt
> +        val user = tokenResponse.body?.userId ?: throw GlobalException(ErrorCode.INVALID_TOKEN_BODY)
일리있네요! 짜면서 약간 헷갈렸는데 service단으로 통일하겠습니다!

2024-04-24 12:25 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/service/ChatService.kt
> +        )
전에 프로젝트할때 프론트에서 여기 코드값으로 케이스를 분류해서 동작을 정의했어서 임시로 넣었습니다!

2024-04-24 12:57 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/service/ChatService.kt
> +        )
적은 양이지만 없다고는 할 수 없죠. 필요한 경우가 생기면 그 때 기능을 추가해볼까요?

2024-04-24 13:00 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/service/ChatService.kt
> +        )
넵 좋습니다!

2024-04-25 04:56 UTC, merged