Feat/read chats
kSideProject/kpring pull request #54
Opened 2024-05-01 11:56 UTC by minisundev

## #️⃣연관된 이슈

#52 

## 📝작업 내용

채팅방별로 채팅을 조회하는 기능을 구현했습니다

## 참고사항
lombok 다음 기능 구현하면서 뺄 예정입니다

2024-05-01 13:03 UTC, yudonggeun approved these changes
좋아요! 다음에는 테스트도 작성해보시죠! 👍👍👍👍👍👍

2024-05-01 13:03 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +        }
수행하고자 하는 기능에 비해서 조회하는 데이터가 많은 것 같아요. findByChatRoomIdAndUserId() 이런 쿼리 한번이면 유효성 검사가 가능해서 시간 복잡도면에서 더 이득 같아서 이런 방법은 어떤가요?

2024-05-01 13:03 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +        }
이거는 추후에 페이징 기능을 추가하면 좋은 것 같아요 👍 👍

2024-05-02 08:37 UTC, vanillacake369 requested changes
![image](https://github.com/kSideProject/kpring/assets/75259783/757fb6cb-b059-4545-95e0-0436264a4c02)

2024-05-02 08:37 UTC, vanillacake369 commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +        }
저도 서비스 레이어의 for loop 보다 DB 레이어의 한 번의 쿼리를 통해서 효율성을 높이는 게 좋겠다고 생각해용 :-)

2024-05-02 08:37 UTC, vanillacake369 commented on chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
> +    val sentAt: LocalDateTime = LocalDateTime.now()
`@MappedSuperclass` 를 통해 Core Base Entity 로 
- 생성시간
- 수정날짜
- 삭제날짜

를 관리할 수 있지 않을까 싶은데 어떻게 생각하시나용 ??

2024-05-02 08:37 UTC, vanillacake369 commented on chat/src/main/kotlin/kpring/chat/chatroom/model/ChatRoom.kt
> +){
이렇게 변경하신 의도가 무엇인지 궁금합니다! 🤔

(제 추측으로는 '조금 더 testable 하게 만들고자 하신 거 아닐까?' 입니다만,,!)

2024-05-02 08:37 UTC, vanillacake369 commented on chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
> +    }
void 로 변경하시거나 메서드 프로세스를 변경하시면 

조금 더 코드의도를 드러낼 수 있지 않을까 싶네용~! :-)

2024-05-07 07:58 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/api/v1/ChatController.kt
> +    }
메서드 명을 수정했습니다~ userId를 가져오는것이 주 목적이기에 void로 바꾸는 것은 안 될 것 같아요

2024-05-07 07:58 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +        }
일리있네요 변경했습니다!

2024-05-07 07:59 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
> +    val sentAt: LocalDateTime = LocalDateTime.now()
좋은 것 같아요~ 변경했습니다!

2024-05-07 08:41 UTC, yudonggeun approved these changes
고생하셨어요!

2024-05-07 08:41 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/global/model/BaseTimeWithUpdateAndDelete.kt
> +}
Jpa가 아닌 mongodb에서도 정상적으로 작동하나요?

2024-05-07 08:41 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
> +    }
생성시간과 수정시간이 있다면 해당 정보를 활용하면 추가적인 값을 관리하지 않아도 가능할 것 같아요.

2024-05-07 08:41 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/global/model/BaseTimeWithUpdateAndDelete.kt
> +abstract class BaseTimeWithUpdateAndDelete : BaseTime() {
basetime에서 관리하는 정보가 createdAt 뿐이라면 그냥 필드에서 주입받아서 사용하는 것이 복잡성을 줄이는 방법이라고 생각이들어요.

deletedAt을 사용한 이유가 궁금하군요!

Entity의 이름이 너무 길어서 조금 더 추상화된 이름을 사용하는 것이 좋아보이네요. 뭐가 좋을까요? 흠....

2024-05-07 08:41 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +        //find chats by chatRoomId and convert them into DTOs
효율적으로 바뀌었군요! 좋아요!

2024-05-07 10:48 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chatroom/model/ChatRoom.kt
> +){
createdAt을 val로 하려고 했는데 생성자로 주입받는 필드가 아닐 때에 var이 아니라 val로 변경하면 java.lang.IllegalStateException: Cannot set property createdAt because no setter, no wither and it's not part of the persistence constructor public kpring.chat.chat.model.Chat(java.lang.String,java.lang.String,java.lang.String)] with root cause 이 에러가 나길래 createdAt을 val로 쓰기 위해서 저렇게 변경해보았었습니다!

2024-05-07 13:28 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
> +    }
일리있네요~~! createdAt과 updatedAt을 생성시에 같은 값으로 초기화하고 둘의 값이 같다면  isEdited() 메서드가 false를 반환하게, 둘의 값이 같다면 true를 반환하게 리팩토링해 보았습니다~

2024-05-07 13:35 UTC, vanillacake369 requested changes
와,,,
1. kotest 가 너무 깔끔하게 잘 짜여서 존경스럽네용 :-0 하루 빨리 테코 짜보면서 연습해봐야겠어요
2. 구현사항이 엄청 많네요!! 너무 고생하셨습니다!!

의문점인 부분부분에 대해서 리플라이 부탁드립니다 :-)

2024-05-07 13:35 UTC, vanillacake369 commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +        }
하나의 메서드가 여러 역할을 수행하고 있어 SRP 위반을 하고 있지 않나 싶네요 :-(

2024-05-07 13:35 UTC, vanillacake369 commented on chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
>          }
body.isValid 값은 누가 던져주고 검증하는걸까요??

2024-05-07 13:35 UTC, vanillacake369 commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
> +        request: CreateChatRoomRequest, userId: String
이런 거 보면 하루 빨리 ktlint 적용해야겠네요 😂

2024-05-07 13:44 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +        }
혹오오옥시 어떤 역할을 수행해서 srp 위반이라고 생각했는지 자세히 알려주실 수 있을까요?

2024-05-07 13:44 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
>          }
auth 모듈에서 검증된 토큰이라면 isValid를 true를 반환해서 작성한 것으로 보여요

2024-05-07 13:44 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
> +        request: CreateChatRoomRequest, userId: String
내일은 ktlint 알아봐야겠네요.

2024-05-07 14:12 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +        }
if (!chatRoomRepository.existsByIdAndMembersContaining(chatRoomId, userId)) {
            throw GlobalException(ErrorCode.UNAUTHORIZED_CHATROOM)
        } 이 부분을 메서드로 분리시켜야 한다는 말씀이실까요?

2024-05-08 07:23 UTC, vanillacake369 approved these changes

2024-05-08 07:23 UTC, vanillacake369 commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +        }
> 혹오오옥시 어떤 역할을 수행해서 srp 위반이라고 생각했는지 자세히 알려주실 수 있을까요?

맞아요. “방의 모든 대화가져오기” 메서드가 다음 로직을 스행하고 있어 분리하는 게 좋지 않을까 싶었어요
1. 검증
2. 가져오기
3. Response 변환

근데 ”굳이 다 뜯어야하나“ 라는 생각도 드네요 🤔

2024-05-08 07:48 UTC, merged