[Chat] 채팅방 나가기 API 구현 : PATCH/api/v1/chatroom
kSideProject/kpring pull request #63
Opened 2024-05-08 14:56 UTC by minisundev

## #️⃣연관된 이슈

#62

## 📝작업 내용

참여하고있던 채팅방에서 나가는 기능을 개발했습니다

2024-05-09 01:07 UTC, yudonggeun requested changes
리뷰입니다 ㅎㅎ

2024-05-09 01:07 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
> +        return userId
유효한 토큰이라면 userId가 존재하는 것은 검증이 되어서 문제가 유효성 검사를 하지 않아도 괜찮아 보여요.
지금은 TokenValidationResponse의 데이터가 userId와 type 뿐이지만 확장된다면 그러한 데이터를 조회할 때마다 지금 구현처럼 매서드를 만들면 다음 코드가 중복될 것 같아요.
```
val body = tokenResponse.body ?: throw GlobalException(ErrorCode.INVALID_TOKEN_BODY)
...
if (!body.isValid) {
            throw GlobalException(ErrorCode.INVALID_TOKEN)
        }
```

2024-05-09 01:07 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
>      }
해당 메서드의 기능이 `chatRoomRepository.findById(chatRoomId)`이랑 동일해 보여서 메서드를 추출하는 것은 조금은 과해보이네요.

2024-05-09 01:07 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/global/model/BaseTime.kt
>          createdAt = now
createdAt도 이러면 갱신되지 않나요?

2024-05-09 02:28 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/model/Chat.kt
> +
오~ 좋네요

2024-05-09 02:28 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chat/service/ChatService.kt
> +            ChatResponse(chat.roomId, chat.isEdited(), chat.createdAt,/*LocalDateTime.now()*/ chat.content)
넴

2024-05-09 02:34 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/global/model/BaseTime.kt
>          createdAt = now
init은 클래스 생성 시점에 딱 한번만 실행되는걸로 알고 있어요

@CreatedDate를 쓰고 있었는데 boolean isUpdated를 빼고
 isUpdated()가 createdAt과 updatedAt이 다른지 보는걸로 업데이트 되었는지 판단하게 하려다 보니까 처음 초기화할때 두 값이 같아져야 돼서 부득이하게 저렇게 만들었습니다

2024-05-09 02:37 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
>      }
그럼 findById를 하면서 null일때 에러를 던지는 것을 코드에 포함시켜도 SRP에 위반되지 않을까요?

2024-05-09 02:37 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/global/model/BaseTime.kt
>          createdAt = now
엔티티는 조회할 때마다 생성되어서 생성 시점에 한번 실행이 되더라도 갱신이 발생할 수도 있을 것 같아요

2024-05-09 06:25 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
> +        return userId
ResponseEntity<TokenValidationResponse> 안에 들어있는 모든 필드를 꺼낼때마다 타입이 optional이라서 ?로 처리를 하지 않으면 에러가 떠요
그래서 필드에 접근할떄마다 ?로 null인 경우 처리를 한 거예요

2024-05-09 07:04 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/global/model/BaseTime.kt
>          createdAt = now
수정해봤어요!

2024-05-10 01:10 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/global/model/BaseTime.kt
>          createdAt = now
> 다시 생각해보니 createdAt을 주입받아서 val로 만들고 init에서 updatedAt에다가 createdAt을 넣으면 될 것 같네요 수정하겠습니다!

이런 방식으로 구현하게 된다면 코드 상으로는 updatedAt은 항상 createdAt과 같아야 한다는 제약을 구현한 것과 같아서 다른 대안이 더 좋은 것 같아요.

isUpdate() 라는 함수 구현을 변경하는 방법도 있을 것 같아요. 갱신된 시간의 차이가 일정 기준 이상이어야지 갱신되었다고 판단하도록 구현하면 해결이 될 것 같아요. 채팅 수정을 사용자가 요청한다면 아무리 적어도 1초의 간격은 있겠죠? (메크로가 아닌 이상?)

2024-05-10 01:19 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
>      }
결합도가 낮을 수록 변경에는 강한 유연한 구조를 가지지만 작은 기능(책임)이 파편화되어 있죠. 근데 이 파편을 만들때 고려해야하는 것은 변경이 되는 것인가? 라는 것이에요. 만약 변경이 거의 없는 기능에 대해서 파편(책임)을 추출해서 구현하게 된다면 유연하지만 그만큼 복잡한 시스템이 되어서 파악하기가 힘들죠.

그래서 책임의 단위를 잘 선정하는 것도 역량이라는 생각합니다. 여기에서는 findById를 하면서 null일때 에러를 던지는 것이 분리해서 구현해야하는 것인가를 고민해보세요.

만약 적절한 이유(가독성이 좋다, 중복된 코드를 제거할 수 있다 등)가 없다면 지금은 분리할 필요가 없는 기능이라고 생각해요.

2024-05-10 01:23 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
> +        return userId
그러면 인증 api를 수정하죠. 유효한 경우에만 해당 타입을 반환하도록 해서 nullable한 필드를 모두 unnullable하게 변경할께요.

2024-05-10 02:18 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chatroom/api/v1/ChatRoomController.kt
> +        return userId
네 좋아요

2024-05-10 02:19 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
>      }
앞으로도 chatRoom을 조회할때 에러를 던지는 부분은 많은 메서드에서 사용할 것 같아서 모든 메서드에 똑같은 부분이 반복되면 코드 중복이 생길 것 같아 미리 분리했습니다

2024-05-10 02:24 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/global/model/BaseTime.kt
>          createdAt = now
수정해봤어요! 의 뜻 : 저렇게 써두고 코드 수정할때는 그냥 CreatedAt이랑 UpdatedAt 쓰게 수정했습니다 UpdatedAt을 맨 처음에는 createdAt의 값을 넣어 초기화하도록 했는데 괜찮은지 코드를 봐주세요~! 근데 지금도 이해가 안 가는데 MySQL 과 JPA를 활용할때는 entity에 default로 값이 들어가 있거나 생성자로 초기화한 값이 생성할때마다 들어가지 않았거든요? init만 
 entity 조회시마다 실행되는 건가요 MongoDB와 Spring 연동의 특징인가요? 그 부분이 명확하게 이해가 안 가네요

2024-05-10 04:30 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/global/model/BaseTime.kt
>          createdAt = now
1. 수정한 코드를 보고 코멘트 남겼어요 ㅠㅠ
2. entity 생성시에는 리플렉션을 통해서 강제로 값을 주입합니다. 그래서 생성한 entity에 조회한 값을 입력하니까
init 실행 이후 조회된 값이 세팅이 되죠. noArgumentConstructor와 같은 기본 생성자를 필수로 요구하는 것도 이러한 맥락에서 필요한 거에요.

2024-05-11 02:04 UTC, yudonggeun approved these changes

2024-05-12 02:13 UTC, yudonggeun commented on chat/build.gradle.kts
> +  invokeInitializers = true
"com.my.Annotation" 이거 경로 수정해야하는 거 아닌가요?

2024-05-12 14:34 UTC, vanillacake369 approved these changes
수고하셨어용 :-) bb

2024-05-12 14:34 UTC, vanillacake369 commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
> +  fun checkIfAuthorized(
check 라는 동사는 '확인한다' 라는 의미를 담고 있어 확인 이후 에러를 던진다라는 것을 예상하기는 어려운 것 같아요.

validate 를 사용하는 게 조금 더 코드의 의미를 담기에 좋은 컨벤션 아닐까?? 조심스럽게 제 생각을 남겨보아요 :-)

> 관련된 좋은 글이 있어 가져와봅니다.
> [validate, verify, is, check 은 언제 어떻게 쓸까?](https://www.inflearn.com/questions/819415/verify-validate-check-is)

2024-05-13 06:39 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
> +  fun checkIfAuthorized(
오~ 좀 더 명확한 단어를 사용할 수 있게 되었어요!

2024-05-13 07:53 UTC, minisundev commented on chat/build.gradle.kts
> +  invokeInitializers = true
그러네요

2024-05-14 02:06 UTC, merged