Feat/get serverinfo
kSideProject/kpring pull request #78
Opened 2024-05-12 06:59 UTC by yudonggeun

## #️⃣연관된 이슈

#77

## 📝작업 내용

- 단순한 서버 조회 기능을 구현하였습니다.
- 권한 인증이나 유효성 검사는 다음 작업에 반영합니다.
- 익숙한 기술인 jpa를 사용하기 위해서 rdb를 이용했지만 서버가 다수의 유저 데이터를 포함한다는 점에서 mongodb를 적용하기로 결정하여 이 부분에 대한 설정을 변경하였습니다.

2024-05-12 14:56 UTC, vanillacake369 reviewed
1. 깔끔한 아키텍처 처리가 굉장히 보기 좋은 것 같아요. 헥사고날 관련해서 열심히 보신 게 보이네요!! 많은 아이디어 얻고 가네요 ㅎㅎㅎ
2. 궁금한 부분이 부분부분 있습니다~! 깔끔한 답변 부탁드릴게요~!
3. PR 청크가 너무 커서 리뷰어가 조금 힘듭니다. ㅠㅠ 조회 API 라서 조회 관련 코드 중심으로 보려고 했는데 compose 구성, 서버 저장, Server 엔티티 정의 등등 있어서 혼동될 수 있겠다 싶네요


고생하셨습다!! :-)

2024-05-12 14:56 UTC, vanillacake369 commented on auth/compose.yml
> +    container_name: "authredis"
컨테이너명을 snake_case 에서 바꾸신 의도가 있으신가요~?

2024-05-12 14:56 UTC, vanillacake369 commented on server/build.gradle.kts
> +    exclude("org.mongodb", "mongo-java-driver")
위 두 의존성을 제외하신 이유는 아래와 같다고 생각했는데 혹시 맞을까요??

> querydsl-mongodb 사용 시, MongoDB와 JPA를 함께 사용하는 경우 org.mongodb:mongo-java-driver와 충돌할 수 있다. 
> 따라서 이를 방지하기 위해 두 의존성을 제외하는 것이다.

2024-05-12 14:56 UTC, vanillacake369 commented on server/src/main/kotlin/kpring/server/adapter/output/mongo/SaveServerPortMongoImpl.kt
> +      ServerEntity(name = req.serverName)
serverName 은 겹쳐도 무관한 걸로 알고 있으면 될까요?

> 가령 UserA 가 "뿡뿡이" 로 방을 만들고
> UserB 가 "뿡뿡이" 로 방을 만들어도
> {id:serverName} 은 {1:"뿡뿡이"}, {2:"뿡뿡이"} 이라서 무관

2024-05-12 14:56 UTC, vanillacake369 requested changes
1. 깔끔한 아키텍처 처리가 굉장히 보기 좋은 것 같아요. 헥사고날 관련해서 열심히 보신 게 보이네요!! 많은 아이디어 얻고 가네요 ㅎㅎㅎ
2. 궁금한 부분이 부분부분 있습니다~! 깔끔한 답변 부탁드릴게요~!
3. PR 청크가 너무 커서 리뷰어가 조금 힘듭니다. ㅠㅠ 조회 API 라서 조회 관련 코드 중심으로 보려고 했는데 compose 구성, 서버 저장, Server 엔티티 정의 등등 있어서 혼동될 수 있겠다 싶네요


고생하셨습다!! :-)

2024-05-13 02:54 UTC, yudonggeun commented
3. 이 부분에 대해서는 고민이 되는 것 같아요. 지금 정해진 스펙을 구현하는 것이 아니라서 말씀하신 것 처럼 도메인도 설정 관련 부분도 연관되어서 바꾸는 것이 불가피 했어요.

청크를 작게 나누기 위해서 도메인을 먼저 설계하고 구현을 하고 다른 기능을 구현을 하는 것이 좋을 까요? 구체적인 개선점이나 의견을 주면 적극적으로 반영하겠습니다.

2024-05-13 02:55 UTC, yudonggeun commented on server/src/main/kotlin/kpring/server/adapter/output/mongo/SaveServerPortMongoImpl.kt
> +      ServerEntity(name = req.serverName)
네 서버 이름은 중첩해서 설정이 가능하도록 구현하고자 합니다.

2024-05-13 03:02 UTC, yudonggeun commented on server/build.gradle.kts
> +    exclude("org.mongodb", "mongo-java-driver")
spring data jpa에서 기본 설정은 rdb를 위한 것이라서 제거를 했고요. 대신 mongodb 전용 spring data 라이브러리가 있기 때문에 해당 라이브러리를 사용하게 되었어요. `@Entity`의 경우에는 querydsl에서 Qclass를 생성할 때, 해당 어노테이션이 적용된 클래스를 대상으로 만들어주기 때문에 사용했는데 `@Document`를 기반으로 생성한느 더 좋은 방식이나 아니면 다른 라이브러리가 있다면 변경하는 것도 좋다고 생각합니다.

2024-05-13 03:03 UTC, yudonggeun commented on auth/compose.yml
> +    container_name: "authredis"
바꾼 기억이 없는데요???? 실수로 바꾼 것 같아요. 개발 환경에서 사용하기 위한 설정이기도 하고 컨테이너 이름을 사용하는 어떠한 서비스도 없어서 크게 신경을 쓰고 있지는 않아요.

2024-05-13 03:05 UTC, yudonggeun commented on server/build.gradle.kts
> +    exclude("org.mongodb", "mongo-java-driver")
다음 글을 읽으면 좀 더 명확할 것 같아요!!
https://stackoverflow.com/questions/31929600/does-mongodb-work-with-jpa

2024-05-14 01:36 UTC, vanillacake369 commented
> 3. 이 부분에 대해서는 고민이 되는 것 같아요. 지금 정해진 스펙을 구현하는 것이 아니라서 말씀하신 것 처럼 도메인도 설정 관련 부분도 연관되어서 바꾸는 것이 불가피 했어요.
> 
> 청크를 작게 나누기 위해서 도메인을 먼저 설계하고 구현을 하고 다른 기능을 구현을 하는 것이 좋을 까요? 구체적인 개선점이나 의견을 주면 적극적으로 반영하겠습니다.

"도멘인을 먼저 설계/구현"PR 이후에 "기능구현"PR 올리시면 좋을 것 같아요~!

필요한 수정사항 없다면 바로바로 Approve 시킬게요~!

2024-05-14 01:37 UTC, vanillacake369 approved these changes

2024-05-14 05:17 UTC, merged