[Chat] 채팅방에 userId로 초대하기 API 구현
kSideProject/kpring pull request #86
Opened 2024-05-15 10:03 UTC by minisundev

## #️⃣연관된 이슈

#84

## 📝작업 내용

존재하는 채팅방에 userId로 멤버를 추가하는 API를 구현했습니다

## 💬리뷰 요구사항

> @PatchMapping("/chatroom/invite/{userId}/chatRoom/{chatRoomId}")
  fun inviteToChatRoomByUserId(
이렇게 했는데 API가 restful한지 의문이 생깁니다
의견 부탁드려요!

2024-05-15 12:13 UTC, yudonggeun approved these changes
💯

2024-05-15 14:44 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
> +
@Transactional을 사용했다가 Persistence Context가 예기치 못하게 비활성화되어 업데이트가 되지 않는 이슈를 겪고 나서 그냥 안전하게 save()를 이용하고 있어요

2024-05-16 01:37 UTC, yudonggeun commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
> +
혹시 동시에 유저를 추가하는 경우에는 어떻게 저장이 될까요?

2024-05-16 01:49 UTC, minisundev commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
> +
오 이미 있는 경우를 생각을 안 했네요 수정하겠습니다

2024-05-16 01:54 UTC, vanillacake369 requested changes

2024-05-16 01:54 UTC, vanillacake369 commented on chat/src/main/kotlin/kpring/chat/chatroom/service/ChatRoomService.kt
> +
> 혹시 동시에 유저를 추가하는 경우에는 어떻게 저장이 될까요?

동근님 말처럼 동시성 이슈를 고려해야하지 않을까 싶네요.
이미 있는 유저인 경우 verifyAuthorizationForChatRoom(,,,) 에서 처리되지만,
동일한 id 에 대해서 동시에 요청하는 경우에 
verifyAuthorizationForChatRoom(,,) 에서 예외처리를 못 하고 중복저장되지 않을까 싶어요.

2024-05-16 04:35 UTC, minisundev commented
verifyAuthorizationForChatRoom(,,,) 에서는 초대받는 유저가 이미 채팅방에 소속되어 있는지 검증하는게 아니라 초대하는 유저가 채팅방에 소속되어 있는지 검증하는 거예요

2024-05-16 04:48 UTC, minisundev commented
일단 있는 유저 초대 안 되게 하고 동시성 이슈를 처리해보겠습니다 지금 개발하고있어요 알겠죠

2024-05-16 09:08 UTC, minisundev commented
동시성 이슈 해결방안 어떤 락을 걸지/ 락을 안 걸고 해결할지 좀 더 생각해보고 있어요

2024-05-29 11:20 UTC, closed without merging